repos:
  - repo: local
    hooks:
      - id: ktlint-check
        name: ktlint
        entry: ./gradlew ktlintCheck
        language: system
        types: [kotlin]
        pass_filenames: false

      - id: detekt
        name: detekt
        entry: ./gradlew detekt
        language: system
        types: [kotlin]
        pass_filenames: false

      - id: android-lint
        name: android lint
        entry: ./gradlew lint
        language: system
        types: [kotlin]
        pass_filenames: false
